marks = []

f1 = int(input("Enter marks here: "))
marks.append(f1)
f1 = int(input("Enter marks here: "))
marks.append(f1)
f1 = int(input("Enter marks here: "))
marks.append(f1)
f1 = int(input("Enter marks here: "))
marks.append(f1)
f1 = int(input("Enter marks here: "))
marks.append(f1)
f1 = int(input("Enter marks here: "))
marks.append(f1)
marks.sort()
print(marks)