s = set()
n = int(input("Enter your value: "))
s.add(int(n))
n = int(input("Enter your value: "))
s.add(int(n))
n = int(input("Enter your value: "))
s.add(int(n))
n = int(input("Enter your value: "))
s.add(int(n))
n = int(input("Enter your value: "))
s.add(int(n))
print(s)